/* Automatically generated by "build-radpaths-h" */
#define LOGDIR		"/opt/radius/var/log/radius"
#define LIBDIR		"/opt/radius/lib"
#define RADDBDIR	"/opt/radius/etc/raddb"
#define RUNDIR		"/opt/radius/var/run"
#define SBINDIR		"/opt/radius/sbin"
#define RADIR		"/opt/radius/var/log/radius/radacct"
#define DICTDIR		"/opt/radius/share/freeradius"
